<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #333;
            margin: 25px;
        }

        .watermark {
            position: fixed;
            top: 40%;
            left: 10%;
            font-size: 65px;
            color: #e5e7eb;
            transform: rotate(-30deg);
            z-index: -1;
        }

        .header {
            background: #1e3a8a;
            color: white;
            text-align: center;
            padding: 15px;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0 0;
            font-size: 12px;
        }

        .report-info {
            margin-bottom: 20px;
        }

        .report-info table {
            width: 100%;
        }

        .report-info td {
            border: none;
            padding: 5px;
        }

        .summary {
            background: #f3f4f6;
            border: 1px solid #d1d5db;
            padding: 10px;
            margin-bottom: 20px;
        }

        .summary h3 {
            margin: 0 0 5px;
            color: #1e3a8a;
        }

        .user-table {
            width: 100%;
            border-collapse: collapse;
        }

        .user-table th {
            background: #2563eb;
            color: white;
            padding: 10px;
            border: 1px solid #ddd;
        }

        .user-table td {
            padding: 8px;
            border: 1px solid #ddd;
            text-align: center;
        }

        .user-table tr:nth-child(even) {
            background: #f9fafb;
        }

        .footer {
            margin-top: 25px;
            text-align: center;
            font-size: 11px;
            color: #666;
            border-top: 1px solid #ccc;
            padding-top: 10px;
        }
    </style>

</head>

<body>

    <div class="watermark">
        BHUSHAN AHIRE
    </div>

    <div class="header">
        <h1>USER MANAGEMENT REPORT</h1>
        <p>Generated By CodeIgniter 4 CRUD System</p>
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td>
                    <strong>Date :</strong>
                    <?= date('d-m-Y') ?>
                </td>

                <td align="right">
                    <strong>Total Users :</strong>
                    <?= count($users) ?>
                </td>
            </tr>
        </table>
    </div>

    <div class="summary">
        <h3>User Summary</h3>

        <p>
            This report contains all registered users available
            in the system database.
        </p>
    </div>

    <table class="user-table">

        <thead>
            <tr>
                <th>ID</th>
                <th>Email Address</th>
                <th>Phone Number</th>
                <th>Password</th>
            </tr>
        </thead>

        <tbody>

            <?php foreach ($users as $row): ?>

                <tr>

                    <td><?= $row['id'] ?></td>

                    <td><?= $row['email'] ?></td>

                    <td><?= $row['phone'] ?? '-' ?></td>

                    <td>********</td>

                </tr>

            <?php endforeach; ?>

        </tbody>

    </table>

    <div class="footer">

        <strong>User Management System</strong><br>

        Generated By : Bhushan Ahire<br>

        Generated On :
        <?= date('d-m-Y H:i:s') ?>

    </div>

</body>

</html>
